### ISSUE TITLE
Include tasks for debugging SU 2019 and 2020

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/sketchup-extension-vscode-project#6]
Currently only 2017 and 2018 are available by default.

**Comment by thomthom** [comment]
Oh, yea, this needs to be kept up to date.

**Comment by thomthom** [comment]
I have started using a single task in newer projects, where the task has options to choose from for each SU version:

https://github.com/SketchUp/sketchup-live-c-api/blob/master/.vscode/tasks.json

Upon first run you'd pick which version, then on consecutive runs you'd Run Last Task.

**Comment by thomthom** [comment]
Fixed as part of 1ef2da8c5a15189447b42edd4e448ae35e3b0be9
